---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO}"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
