---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
    image: quay.io/rockylinux/rockylinux:8.7.20221112
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
