---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: geerlingguy/docker-rockylinux8-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
