---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: registry.redhat.io/ubi8:8.7-1090
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
