---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check packages installed
      ansible.builtin.assert:
        that:
          - "item in ansible_facts.packages"
        success_msg: "{{ item }} version installed: {{ ansible_facts.packages[item][0]['version'] }}"
        fail_msg: "{{ item }} is not installed"
      loop:
        - podman
        - buildah
        - skopeo
