---
name: Molecule Test
on: [push, pull_request]

defaults:
  run:
    working-directory: 'ansible-podman'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: 'ansible-podman'

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install yamllint dependencies
        run: pip3 install yamllint

      - name: Check code syntax with yamllint
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        distro:
          - "quay.io/rockylinux/rockylinux:8.7.20230215"
          - "quay.io/rockylinux/rockylinux:9.1.20230215"
          - "quay.io/rockylinux/rockylinux:8.7.20230215-ubi"
          - "quay.io/rockylinux/rockylinux:9.1.20230215-ubi"
          - "redhat/ubi8:8.8-854"
          - "redhat/ubi9:9.2-489"

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: 'ansible-podman'

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install molecule dependencies
        run: |
          pip3 install ansible molecule[podman]==4.0.4 podman==4.4.1 ansible-compat==4.0.1

      - name: Run molecule test
        run: |
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
